#!/bin/bash

function sport {

# Named "sport" because red means "fast"

local WHITE="\[\033[1;37m\]"
local LIGHT_BLUE="\[\033[1;34m\]"
local YELLOW="\[\033[1;33m\]"
local RED="\[\033[1;31m\]"
local NO_COLOUR="\[\033[0m\]"

case $TERM in
    xterm*|rxvt*)
        TITLEBAR='\[\033]0;\u@\h:\w\007\]'
        ;;
    *)
        TITLEBAR=""
        ;;
esac

PS1="$TITLEBAR\
$LIGHT_BLUE[\
$WHITE\u$LIGHT_BLUE@$WHITE\h\
$LIGHT_BLUE]-[\
$WHITE\$PWD\
$LIGHT_BLUE]\
\n\
$LIGHT_BLUE[\
$WHITE\D{%H:%M}$LIGHT_BLUE]$ $NO_COLOUR"

PS2="$RED-$WHITE-$WHITE-$NO_COLOUR "

}
